spring:
  profiles:
    active:
      # ?? ?? ? ???? ???? ??
      # - test / dev / prod ?? ??? ??? Bean(@Profile) ??? ?? ? ??
      #      - test
      - dev

  autoconfigure:
    # Spring Boot? ?? ??(AutoConfiguration) ??? ?? ??? ??
    # SecurityAutoConfiguration(?? ?? ????)? ????
    # ?? ??? ???/?? ?? ?? ???? ??
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  application:
    # ?????? ??
    # ??/Actuator/?? ???? ???? ??? ?
    name: spring-bean-practice

  jackson:
    serialization:
      # JSON ??? ? ?? ??? ?? ?? ???? ??
      # spring.jackson.serialization.indent-output=true ? ??? ??
      # (ObjectMapper? INDENT_OUTPUT ??? ??)
      indent-output: true

my:
  # ??? ?? ???? ??
  # @Value("${my.greeting}") ?? @ConfigurationProperties(prefix="my")? ?? ??

  # example12 / example14?? Environment.getProperty("my.greeting")? ?? ?
  greeting: "Hello, Codeit Spring Bootcamp!"

  boolean: false
  number: 1234

  # ??? 1?? ??? ?? ??(?? ??)
  # ? @Value? String?? ???, ?? split?? ?? ??
  servers: "dev.example.com,prod.example.com,local.example.com"

  service:
    # example13: @ConfigurationProperties(prefix="my.service")? ????? ??
    #    name: "SpringDocs"

    # ???? ?? ??
    # ${ZSH}? "???? ZSH" ?? ???? my.service.name? ???
    # ????? ??? ??? ??/? ?? ? ? ??? ??
    name: "${ZSH}"

    port: 8081
    enabled: true

  storage:
    # example13: StorageProperties(@ConfigurationProperties(prefix="my.storage"))
    path: /data/files
    s3:
      bucket: my-bucket
      region: ap-northeast-2

  auth:
    # example13: AuthProperties(@ConfigurationProperties(prefix="my.auth")) + @Validated
    # clientId: @NotBlank
    # retryCount: @Min(1)
    clientId: "kim luc ky Id"
    retryCount: 3

  valid:
    # example19: ValidTest(@ConfigurationProperties("my.valid")) + @Validated
    # name: @ValidName(??? ??) ?? ??
    name: "asd"

  settings:
    # example13: MySettings(@ConfigurationProperties(prefix="my"))??
    # settings: Map<String, String>?? ?? ????
    # ?? ??? ???? ???? ????? ???? ?? ??
    # (Map<String,String>?? true/20? ???? ???)
    cache: true
    maxConnections: 20

  hosts:
    # example13: HostListProperties(@ConfigurationProperties(prefix="my"))??
    # hosts: List<Host> ??? ????? ??
    - host: dev.example.com
      port: 8080
    - host: prod.example.com
      port: 80
    - host: local.example.com
      port: 8888

server:
  # ?? ?? ?? ?? ??
  # example14?? Environment.getProperty("server.port")? ?? ?
  port: 8080

config:
  # ??? ??? ??(?? ???? ?? ???? ???? ??? ?? ??)
  timeout: 3000

custom:
  # example16: FeatureXEnabledCondition?? ?? ?
  # custom.feature-x=true ? ?? FeatureService Bean? ???
  # false?? FeatureService? ?? ???? ??? getBean ? ?? ?? ??
  feature-x: false
