## ===============================
## Spring Boot ?? ??
## ===============================
#
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#
#spring.application.name=spring-bean-practice
#
#spring.jackson.serialization.indent-output=true
#
#
## ===============================
## ??? ?? my.* ??
## ===============================
#
#my.greeting=Hello, Codeit Spring Bootcamp!
#my.boolean=false
#my.number=1234
#my.servers=dev.example.com,prod.example.com,local.example.com
#
#
## ---- my.service ----
## my.service.name=SpringDocs
#my.service.name=${ZSH}
#my.service.port=8081
#my.service.enabled=true
#
#
## ---- my.storage ----
#my.storage.path=/data/files
#my.storage.s3.bucket=my-bucket
#my.storage.s3.region=ap-northeast-2
#
#
## ---- my.auth ----
#my.auth.clientId=kim luc ky Id
#my.auth.retryCount=3
#
#
## ---- my.settings ----
#my.settings.cache=true
#my.settings.maxConnections=20
#
#
## ---- my.hosts (List) ----
#my.hosts[0].host=dev.example.com
#my.hosts[0].port=8080
#
#my.hosts[1].host=prod.example.com
#my.hosts[1].port=80
#
#my.hosts[2].host=local.example.com
#my.hosts[2].port=8888
#
#
## ===============================
## Server ??
## ===============================
#
#server.port=8080
#
#
## ===============================
## ?? ??
## ===============================
#
#config.timeout=3000
